#!/bin/bash
#
# Known problems:
#
#     entries containing a '&' will throw errors. Unknown -
#     at this time if it's a openbox or script issue
#
# add to menus like openbox with a like this:
# <menu execute="script-name /path/to/files/" id="script-name" label="menu name"/>
#
echo "<openbox_pipe_menu>"
echo '<item label="Scripts folder"><action name="Execute"><command>'
echo 'thunar '$1
echo '</command></action></item>'
echo '<separator label="Folders"/>'
list1="$(ls -F $1 | grep -F '/')"
for f1 in $list1
do
echo '<menu id="'$f1
echo '" label="'
echo $f1
echo '">'
#pulling conkyrc list from folders
list2="$(ls $1/$f1)"
for f2 in $list2
do
#menu start
echo '<menu id="'$f2
echo '" label="'
echo $f2
echo '">'
#run script
echo '<item label="Run:'
echo $f2
echo '"><action name="Execute"><command>'
echo $1/$f1$f2
echo '</command></action></item>'
#edit script
echo '<item label="edit:'
echo $f2
echo '"><action name="Execute"><command>'
echo 'geany '$1/$f1$f2
echo '</command></action></item>'
#end of menu
echo '</menu>'
done
#done for pulling folder list
echo '</menu>'
done
echo '<separator label="single configs"/>'
#pulling conkyrc list from conky folder
list3="$(ls $1)"
for f3 in $list3
do
#menu start
echo '<menu id="'$f3
echo '" label="'
echo $f3
echo '">'
#conky start
echo '<item label="Run:'
echo $f3
echo '"><action name="Execute"><command>'
echo 'conky -c '$1/$f3
echo '</command></action></item>'
#edit conky
echo '<item label="edit:'
echo $f3
echo '"><action name="Execute"><command>'
echo 'geany '$1/$f3
echo '</command></action></item>'
#end of menu
echo '</menu>'
done
echo "</openbox_pipe_menu>"
exit
