#!/bin/bash
#
# Known problems:
#
#     entries containing a '&' will throw errors. Unknown -
#     at this time if it's a openbox or script issue
#
# add to menus like openbox with a like this:
# <menu execute="script-name /path/to/files/" id="script-name" label="menu name"/>
#
#locking path
case "$1" in
  */)
    declare -r path=$1
    ;;
  *)
    declare -r path=$1/
    ;;
esac
function icall () {
  local label="$1"
  # sanatizing name
  label=("${label//</&lt;}")
  label=("${label//&/&amp;}")
  label=("${label//>/&gt;}")
  label=("${label//\"/&quot;}")
  label=("${label//\'/&apos;}")
  label=("${label//_/__}")
  echo '<item label="'$label'"><action name="Execute"><command>' ;}
function iend () { echo '</command></action></item>' ;}
function separator () {
  if [ -z "$*" ]; then
  echo '<separator/>'
  else
  local label="$1"
  # sanatizing name
  label=("${label//</&lt;}")
  label=("${label//&/&amp;}")
  label=("${label//>/&gt;}")
  label=("${label//\"/&quot;}")
  label=("${label//\'/&apos;}")
  label=("${label//_/__}")
  echo '<separator label="'$label'"/>'
  fi ;}
# start of menu
echo "<openbox_pipe_menu>"
  status=$(pidof mocp)
  if [[ -z $status ]]; then
    #start music player, because it isn't running
    icall "Start MOCP"
      echo 'terminator -T "MOCP" -e "mocp"'
    iend
  else
    #show song name
    title="$(mocp -Q 'MOC [%state]') $(mocp -Q %file | awk -F'/' '{print $NF}')"
    #~ title="$(mocp -Q 'MOC [%state] %song')"
    separator "$title"
    #controls
    icall "Play / Pause"
      echo "mocp -G"
    iend
    icall "Next"
      echo "mocp -f"
    iend
    icall "Previous"
      echo "mocp -r"
    iend
    separator
    #open music player
    icall "Open MOCP"
      echo 'terminator -T "MOCP" -e "mocp"'
    iend
    #link to path
    icall "Music Folder"
      echo 'thunar '$path''
    iend
    #kill mocp
    icall "Kill Mocp"
      echo 'mocp -x'
    iend
  fi
#end of pipemenu
echo "</openbox_pipe_menu>"
exit
